### PR TITLE
Bump version to v1.0.0-beta.1.0

### PR DESCRIPTION
**Pull request by feltech**
Closes https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/issues/124.

### CODE REVIEW

**Review by foundry-markf — APPROVED** [review]
Looks fine, but just calling out you seem to have a different versioning scheme to openassetio betas, e.g. https://github.com/OpenAssetIO/OpenAssetIO/tags shows,

* v1.0.0-beta.2.2
* v1.0.0-beta.2.1

so where is this `rev` coming from?

Actually, looking closer, looks like you've got one convention in Git tags, but another in Python versions, as I just spotted this here
```
dependencies = ["openassetio>=1.0.0b2.rev2"
```

**Comment by feltech** [comment]
> Looks fine, but just calling out you seem to have a different versioning scheme to openassetio betas, e.g. https://github.com/OpenAssetIO/OpenAssetIO/tags shows,
> 
>     * v1.0.0-beta.2.2
> 
>     * v1.0.0-beta.2.1
> 
> 
> so where is this `rev` coming from?
> 
> Actually, looking closer, looks like you've got one convention in Git tags, but another in Python versions, as I just spotted this here
> 
> ```
> dependencies = ["openassetio>=1.0.0b2.rev2"
> ```

Yeah you got it. When we decided to use semver for beta versions, i.e. `-beta.x.y`, we found that's not directly supported by PyPI/PEP versioning.  The closest we could get was a ["post-release segment"](https://peps.python.org/pep-0440/#public-version-identifiers) (we prefer the synonym  "rev", but if you [look on PyPI](https://pypi.org/project/openassetio/) it uses "post" regardless :disappointed: )

**Comment by foundry-markf** [comment]
That concerns me with the reference to 'post', as it's meant to mean no behaviour changes, just like a docs fixup that was found to be in error.

https://peps.python.org/pep-0440/#post-releases

Their note
> The use of post-releases to publish maintenance releases containing actual bug fixes is strongly discouraged. In general, it is better to use a longer release number and increment the final component for each maintenance release.

My experiences of pre-releases on PyPi come from cruiz, and I've done a few, but I keep it simple with a semver + aN/bN where N is a monotonically increasing integer.

https://github.com/markfinal/cruiz/releases

I then keep Git tags and PyPi release numbers in sync.

Just saying :)

**Comment by feltech** [comment]
> That concerns me with the reference to 'post', as it's meant to mean no behaviour changes, just like a docs fixup that was found to be in error.
> 
> https://peps.python.org/pep-0440/#post-releases
> 
> Their note
> 
> > The use of post-releases to publish maintenance releases containing actual bug fixes is strongly discouraged. In general, it is better to use a longer release number and increment the final component for each maintenance release.

It is a bit of a square peg round hole issue.  We primarily focussed on [semver where our scheme is fine](https://semver.org/#spec-item-9), and then shimmed the Python versioning as best we could to fit :cry:

Like I said previously, given the length of the beta period, and that we expected products would be shipping with it and/or pipelines using it, we needed to convey breaking vs. non-breaking changes in the beta version identifier. I think once 1.0.0 is reached proper, future pre-releases, if any, can be shorter-lived, not used in production, and so use a single incrementing number.

**Pull request merged**
